### ISSUE TITLE
fyi similar code

### ISSUE THREAD

**Issue by ailin-nemui** [Dica-Developer/slack-irssi#1]
https://github.com/ailin-nemui/slack-irssi

maybe you can use or combine it, the orig. author doesn't need it anymore

**Comment by JayGray** [comment]
@ailin-nemui,

thanks for the hint. Never crossed my mind to do the obvious, search GitHub for existing projects. ;)

Had a look into it and already borrowed some ideas.
Curious, what lets you assume the author doesn't need the code anymore?

**Comment by ailin-nemui** [comment]
https://github.com/tedski/slack-irssi/issues/20
